export enum BaseStates {
  SUCCESS,
  ERROR,
  LOADING
}

export enum SimpleLoginStates {
  SUCCESS,
  ERR_EMAIL_NOT_PROVIDED,
  ERR_PASSWORD_NOT_PROVIDED,
  ERR_INVALID_EMAIL,
  ERR_PASSWORD_TOO_SHORT,
  ERR_UNKNOWN,
  ERR_EMAIL_NOT_FOUND,
  ERR_INCORRECT_PASSWORD,
  ERR_USER_USES_OAUTH
}

export enum SignupStates {
  SUCCESS,
  ERR_EMAIL_NOT_PROVIDED,
  ERR_PASSWORD_NOT_PROVIDED,
  ERR_NAME_NOT_PROVIDED,
  ERR_PASSWORDS_DONT_MATCH,
  ERR_INVALID_EMAIL,
  ERR_INVALID_NAME,
  ERR_PASSWORD_TOO_SHORT,
  ERR_NAME_TOO_SHORT,
  ERR_ALREADY_EXISTS,
  ERR_UNKNOWN
}

export const ErrorToString = {
  "00x01": "ENV_NOT_SET",
  "01x01": "UNKNOWN",
  "01x02": "ABORTED",
  "01x03": "ALREADY_EXISTS",
  "01x400": "INVALID",
  "01x403": "UNAUTHORIZED",
  "01x404": "NOT_FOUND"
} as const;
export type ErrorCodes = keyof typeof ErrorToString; 
