export enum BaseStates {
  SUCCESS,
  ERROR,
  LOADING
}

export enum SimpleLoginStates {
  SUCCESS,
  ERR_EMAIL_NOT_PROVIDED,
  ERR_PASSWORD_NOT_PROVIDED,
  ERR_INVALID_EMAIL,
  ERR_PASSWORD_TOO_SHORT,
  ERR_UNKNOWN,
  ERR_EMAIL_NOT_FOUND,
  ERR_INCORRECT_PASSWORD,
  ERR_USER_USES_OAUTH
}

export enum SignupStates {
  SUCCESS,
  ERR_EMAIL_NOT_PROVIDED,
  ERR_PASSWORD_NOT_PROVIDED,
  ERR_NAME_NOT_PROVIDED,
  ERR_PASSWORDS_DONT_MATCH,
  ERR_INVALID_EMAIL,
  ERR_INVALID_NAME,
  ERR_PASSWORD_TOO_SHORT,
  ERR_NAME_TOO_SHORT,
  ERR_ALREADY_EXISTS,
  ERR_UNKNOWN
}

export const PB_Codes = {
  200: "SUCCESS",
  400: "MISSING_FIELD",
  403: "UNAUTHORIZED"
} as const;
export type t_PB_Code = (typeof PB_Codes)[keyof typeof PB_Codes];
